# Generated by Django 6.0.2 on 2026-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='seat_requested',
            field=models.IntegerField(default=1),
        ),
    ]
