# Generated by Django 5.2.11 on 2026-02-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_bookingdata_seat_requested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdata',
            options={'verbose_name': 'Booking Data', 'verbose_name_plural': 'Booking Data'},
        ),
    ]
